### ISSUE TITLE
Bug: 'txt' instead of 'text' for `text_completion_dataset`

### ISSUE THREAD

**Issue by SimiPixel** [pytorch/torchtune#1028] opened 2024-05-28 22:15 UTC
In the tutorial on datasets (https://pytorch.org/torchtune/main/tutorials/datasets.html#custom-unstructured-text-corpus) both in the config and the code example the `source` keyword should be `text` and not `txt`

```yaml
# YAML config
dataset:
  _component_: torchtune.datasets.text_completion_dataset
  source: text 
  data_files: path/to/my_data.txt
```

**Comment by RdoubleA** [comment] 2024-05-28 23:21
Ah good catch. Thank you @SimiPixel for flagging this. Feel free to open a PR to fix this and I can review it if you'd like :) Or I can go ahead and patch it, whichever you prefer.

**Comment by SimiPixel** [comment] 2024-05-29 08:06
Yes, i can do that, however, there is still a couple of other things that are not working correctly here. Let me elaborate:
Let's assume we start with newest Pytorch (v2.3.0) installed and with torchtune installed from git at the time of 28.05.24.

---
>  tune run full_finetune_single_device --config llama3/8B_full_single_device
```
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torchtune/config/_parse.py", line 50, in wrapper
    sys.exit(recipe_main(conf))
             ^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/recipes/full_finetune_single_device.py", line 504, in recipe_main
    recipe.setup(cfg=cfg)
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/recipes/full_finetune_single_device.py", line 201, in setup
    self._optimizer = self._setup_optimizer(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/recipes/full_finetune_single_device.py", line 283, in _setup_optimizer
    optim_dict = {
                 ^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/recipes/full_finetune_single_device.py", line 284, in <dictcomp>
    p: config.instantiate(cfg_optimizer, [p])
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torchtune/config/_instantiate.py", line 106, in instantiate
    return _instantiate_node(config, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torchtune/config/_instantiate.py", line 29, in _instantiate_node
    _component_ = _get_component_from_path(node.get("_component_"))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torchtune/config/_utils.py", line 76, in _get_component_from_path
    raise InstantiationError(
torchtune.config._errors.InstantiationError: Error loading 'bitsandbytes.optim.PagedAdamW8bit':
ModuleNotFoundError("No module named 'bitsandbytes'")
Are you sure that module 'bitsandbytes' is installed?
```

Not sure if this is on purpose but it seems weird? Why include additional dependencies in the arguably most fundamental examples?

---

> tune run lora_finetune_single_device --config llama3/8B_lora_single_device dataset=torchtune.datasets.text_completion_dataset dataset.source=txt dataset.data_files=my_data.txt

```
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torchtune/datasets/_text_completion.py", line 111, in text_completion_dataset
    return TextCompletionDataset(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torchtune/datasets/_text_completion.py", line 41, in __init__
    self._data = load_dataset(source, **load_dataset_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/datasets/load.py", line 2587, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/datasets/load.py", line 2259, in load_dataset_builder
    dataset_module = dataset_module_factory(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/datasets/load.py", line 1904, in dataset_module_factory
    raise e1 from None
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/datasets/load.py", line 1850, in dataset_module_factory
    raise DatasetNotFoundError(
datasets.exceptions.DatasetNotFoundError: Dataset 'txt' doesn't exist on the Hub or cannot be accessed. If the dataset is private or gated, make sure to log in with `huggingface-cli login` or visit the dataset page at https://huggingface.co/datasets/txt to ask for access.
```

Okay, replacing `txt` with `text`

---

> tune run lora_finetune_single_device --config llama3/8B_lora_single_device dataset=torchtune.datasets.text_completion_dataset dataset.source=text dataset.data_files=my_data.txt

```
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torchtune/datasets/_text_completion.py", line 111, in text_completion_dataset
    return TextCompletionDataset(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torchtune/datasets/_text_completion.py", line 41, in __init__
    self._data = load_dataset(source, **load_dataset_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/datasets/load.py", line 2587, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/datasets/load.py", line 2296, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/datasets/builder.py", line 374, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/datasets/builder.py", line 612, in _create_builder_config
    builder_config = self.BUILDER_CONFIG_CLASS(**config_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TextConfig.__init__() got an unexpected keyword argument 'train_on_input'
```

Let's copy the config and create a custom config `my_8B_lora_single_device.yaml` which has the line `train_on_input` deleted.

---

> tune run lora_finetune_single_device --config my_8B_lora_single_device.yaml dataset=torchtune.datasets.text_completion_dataset dataset.source=text dataset.data_files=my_data.txt

```
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/recipes/lora_finetune_single_device.py", line 559, in recipe_main
    recipe.train()
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/recipes/lora_finetune_single_device.py", line 464, in train
    for idx, batch in enumerate(self._dataloader):
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torchtune/datasets/_text_completion.py", line 49, in __getitem__
    sample = self._data[index]
             ~~~~~~~~~~^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/datasets/dataset_dict.py", line 81, in __getitem__
    raise KeyError(
KeyError: "Invalid key: 0. Please first select a split. For example: `my_dataset_dictionary['train'][0]`. Available splits: ['train']"
0it [00:00, ?it/s]
```

I just guessed to add `dataset.split=train`

---

> tune run lora_finetune_single_device --config my_8B_lora_single_device.yaml dataset=torchtune.datasets.text_completion_dataset dataset.source=text dataset.data_files=my_data.txt dataset.split=train

```
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/recipes/lora_finetune_single_device.py", line 559, in recipe_main
    recipe.train()
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/recipes/lora_finetune_single_device.py", line 464, in train
    for idx, batch in enumerate(self._dataloader):
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torchtune/datasets/_text_completion.py", line 50, in __getitem__
    return self._prepare_sample(sample)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torchtune/datasets/_text_completion.py", line 54, in _prepare_sample
    tokens = self._tokenizer.encode(text=prompt, add_bos=True, add_eos=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/vy43meti/miniforge3/envs/llama3/lib/python3.11/site-packages/torchtune/modules/tokenizers/_tiktoken.py", line 251, in encode
    substr = text[i : i + MAX_ENCODE_CHARS]
             ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'slice'
0it [00:00, ?it/s]
```

This is where i gave up. I am not sure, maybe my data requires some specific formatting. But i don't believe so because it is not documented and no examplary content of `my_data.txt` provided.
Mine was just some sentences without any special identifiers like [EOS].

Maybe somebody knows what the problem is?

**Comment by SimiPixel** [comment] 2024-05-29 08:11
#1021 sorry i did not see this issue, but this is related

**Comment by RdoubleA** [comment] 2024-05-29 13:24
I'm sorry this was difficult for you and apologies the tutorial had this many roadblocks. Appreciate you walking through the issues step by step. I will follow your exact flow from a fresh install and see what I can clean up.

> Not sure if this is on purpose but it seems weird? Why include additional dependencies in the arguably most fundamental examples?

This error is expected because the config uses an optimizer from bitsandbytes to reduce memory and fit on a single device. It is an extra dependency that we ask users to install separately if they would like to run the config. As you rightly pointed out, this should not be the example for the tutorial. I can update this.

> Let's copy the config and create a custom config my_8B_lora_single_device.yaml which has the line train_on_input deleted.

You ran the command from the tutorial using the CLI overrides. Unfortunately, overriding the dataset component does not remove the `train_on_input` parameter that's default in all our configs, and `text_completion_dataset` does not use this. This highlights an issue we've been hitting before where we may want to enable removing parameters from the config with a CLI override, something similar to [what Hydra does](https://hydra.cc/docs/advanced/override_grammar/basic/#modifying-the-config-object) (cc @ebsmothers). I'll need to revise these examples to avoid this issue or just resolve it. But in general your approach of copying the config and modifying it directly was the right approach.

> I just guessed to add dataset.split=train

We had a recent update to add `split=train` to any custom dataset as it is required by Hugging Face (see #1004) but it seems like this tutorial landed in parallel and wasn't updated. I will add this parameter to all the examples.

> This is where i gave up. I am not sure, maybe my data requires some specific formatting. But i don't believe so because it is not documented and no examplary content of my_data.txt provided.

This error is strange and seems to be an issue in processing your data, but you raise a good point that it might be good to show an example `my_data.txt`. Let me see if I can reproduce this and will update you.

**Closed** 2024-07-20 20:54 UTC
