### ISSUE TITLE
v0.3 regression, full_finetune_distributed slower ?

### ISSUE THREAD

**Issue by Delaunay** [pytorch/torchtune#1718] opened 2024-09-30 14:24 UTC
The recipe [full_finetune_distributed](https://github.com/pytorch/torchtune/blob/v0.3.0/recipes/full_finetune_distributed.py)
Appear to be much slower in v0.3 than [v0.2.1](https://github.com/pytorch/torchtune/blob/v0.2.1/recipes/full_finetune_distributed.py)

Everything seems to work as usual, but my job that used to work in v0.2.1 time out in v0.3.0.

I don't have much detail yet, but maybe as you are more familiar with the code base you could have an idea already based on what changed recently!

**Comment by joecummings** [comment] 2024-09-30 15:07
Can you share a few more details around which models you're using, size of dataset, machine type?

**Comment by Delaunay** [comment] 2024-09-30 18:37
I tried on 

* 8xA100 and 8xH100, 
* model is `torchtune.models.llama3_1.llama3_1_70b` 
* dataset is torchtune.datasets.alpaca_dataset

**Comment by joecummings** [comment] 2024-10-02 12:02
Hey @Delaunay - I looked into this and was able to repro! Unfortunately, still digging into the root cause, but a quick fix is to upgrade your PyTorch version to the nightlies. 

```
pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/
```

After doing this, training should be fast again:
<img width="1727" alt="Screenshot 2024-10-02 at 1 01 42 PM" src="https://github.com/user-attachments/assets/809c8cfd-bc69-47dc-97b3-550b8050ebd4">

**Comment by ebsmothers** [comment] 2024-10-08 04:33
I think @felipemello1 added some warnings about this in #1733, seems like the fix is to run on PyTorch nightlies here. Given that we have a resolution for this I am gonna close the issue, but @Delaunay if you are not unblocked please feel free to reopen.

**Comment by Delaunay** [comment] 2024-10-08 15:35
I downgraded to `0.2.1` while I wait for pytorch to release a new version, in my case I cannot use nightlies.

But if it OOM why did I not see the error being raised ? 
Is it linked to the CPU offloading where things get moved out to CPU to avoid OOM and it gets super slow but eventually OOM ?

**Comment by ebsmothers** [comment] 2024-10-09 15:53
@Delaunay since you can't use the nightlies I'll reopen this. The main change is that between 0.2.1 and 0.3.0 we moved onto FSDP2. Since this is a relatively new feature, it's likely that there have been some optimizations made since 2.4 (I can't pinpoint anything offhand but can dig in further here). Out of curiosity, where is it slow? Is it during training, checkpoint load, or somewhere else? And do you see similar slowdowns when running on smaller models (i.e. ones where we aren't doing CPU offload)?

**Closed** 2024-12-10 11:38 UTC
